apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observabilidade
  namespace: plataforma-m-mais
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts  # Repositório Helm
    chart: kube-prometheus-stack  # Nome do Helm Chart
    targetRevision: 54.2.2  # Versão específica do chart
    path: sistemas/plataforma-m-mais/manifestos/observabilidade
    helm:
      valueFiles:
        - namespace.yaml  # Configuração de namespace
        - values-sandbox.yaml  # Configurações específicas para o ambiente sandbox
  destination:
    server: https://kubernetes.default.svc  # Cluster de destino
    namespace: observabilidade  # Namespace onde será implantado
    createNamespace: true  # Cria o namespace automaticamente
  syncPolicy:
    automated:
      prune: true  # Remove recursos não utilizados
      selfHeal: true  # Corrige automaticamente alterações manuais
