apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: argocd-virtualservice
  namespace: plataforma-m-mais
spec:
  hosts:
    - "argocd.plataformammais-sandbox.n-mercantil.com.br"  # O mesmo domínio configurado no Gateway
  gateways:
    - istio-system/istio-ingressgateway
  http:
    - match:
        - uri:
            prefix: "/"  # Roteia todo o tráfego para o NGINX
      route:
        - destination:
            host: argocd-server  # O nome do Service do NGINX
            port:
              number: 80
