apiVersion: v1
kind: Namespace
metadata:
  name: observabilidade
  labels:
    environment: sandbox
    app: observability-stack
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: observabilidade
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      nodeSelector:
        layer: apps  # Afinidade com NodePool "apps"
      containers:
        - name: prometheus
          image: prom/prometheus:latest
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-storage
              mountPath: /prometheus
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--storage.tsdb.retention=15d"
            - "--web.enable-lifecycle"
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prometheus-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: observabilidade
  labels:
    app: prometheus
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
      name: http
  selector:
    app: prometheus
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: observabilidade
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi  # Volume persistente para Prometheus
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: prometheus-virtualservice
  namespace: observabilidade
spec:
  hosts:
    - prometheus.plataformammais-sandbox.n-mercantil.com.br
  gateways:
    - istio-system/istio-ingressgateway  # Istio Gateway usado para rotear o tráfego
  http:
    - match:
        - uri:
            prefix: "/"
      route:
        - destination:
            host: prometheus
            port:
              number: 9090
