apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Namespace","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app.kubernetes.io/instance":"az-agent"},"name":"plataforma-m-mais"},"spec":{},"status":{}}
  creationTimestamp: "2024-10-15T18:08:38Z"
  deletionTimestamp: "2024-10-17T20:30:57Z"
  labels:
    app.kubernetes.io/instance: az-agent
    kubernetes.io/metadata.name: plataforma-m-mais
  name: plataforma-m-mais
  resourceVersion: "3493945"
  uid: 39ceb94a-d98a-4099-9871-555f408e0f2b
spec:
  finalizers:
  - kubernetes
status:
  conditions:
  - lastTransitionTime: "2024-10-17T20:31:07Z"
    message: All resources successfully discovered
    reason: ResourcesDiscovered
    status: "False"
    type: NamespaceDeletionDiscoveryFailure
  - lastTransitionTime: "2024-10-17T20:31:07Z"
    message: All legacy kube types successfully parsed
    reason: ParsedGroupVersions
    status: "False"
    type: NamespaceDeletionGroupVersionParsingFailure
  - lastTransitionTime: "2024-10-17T20:31:07Z"
    message: All content successfully deleted, may be waiting on finalization
    reason: ContentDeleted
    status: "False"
    type: NamespaceDeletionContentFailure
  - lastTransitionTime: "2024-10-17T20:31:07Z"
    message: 'Some resources are remaining: applications.argoproj.io has 2 resource
      instances'
    reason: SomeResourcesRemain
    status: "True"
    type: NamespaceContentRemaining
  - lastTransitionTime: "2024-10-17T20:31:07Z"
    message: 'Some content in the namespace has finalizers remaining: resources-finalizer.argocd.argoproj.io
      in 2 resource instances'
    reason: SomeFinalizersRemain
    status: "True"
    type: NamespaceFinalizersRemaining
  phase: Terminating
