apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observabilidade
  namespace: plataforma-m-mais
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://devops.mercantil.com.br/Tecnologia_MB/MB/_git/MB.DVX.AppOfApps.PlataformaM_Mais
    path: sistemas/plataforma-m-mais/manifestos/observabilidade
    targetRevision: HEAD
    helm:
      valueFiles:
        - namespace.yaml
        - values-sandbox.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: observabilidade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  namespaceResource:
    createNamespace: true
