apiVersion: v1
kind: Secret
metadata:
  name: azdevops
  namespace: azure-devops-agents
type: Opaque
data:
  AZP_URL: aHR0cHM6Ly9kZXYuYXp1cmUuY29tL3lvdXItb3JnYW5pemF0aW9u # Base64 encoded value
  AZP_TOKEN: eW91ci1wYXQtdG9rZW4= # Base64 encoded value
  AZP_POOL: eW91ci1hZ2VudC1wb29s # Base64 encoded value
