---
apiVersion: v1
kind: Secret
metadata:
  name: azdevops
  namespace: plataforma-m-mais
type: Opaque
data:
  AZP_URL: aHR0cHM6Ly9kZXZvcHMubWVyY2FudGlsLmNvbS5ici9UZWNub2xvZ2lhX01CCg==
  AZP_TOKEN: ZzI3YXg2ZG41aHhxbDRvM3JlNTV5eHM3NGVocnB0bHJhdXFoNTZiaTR1N2F6dXZvendwcQo=
  AZP_POOL: YWdlbnQtZHZ4LWdrZQo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azdevops-deployment
  namespace: plataforma-m-mais
  labels:
    app: azure-agent-gke-dvx
spec:
  replicas: 2  # Mantenha sempre duas réplicas ativas para alta disponibilidade
  selector:
    matchLabels:
      app: azure-agent-gke-dvx
  template:
    metadata:
      labels:
        app: azure-agent-gke-dvx
    spec:
      containers:
        - name: kubepodcreation
          image: imagensmbprd.azurecr.io/agent:189170
          env:
            - name: AZP_URL
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: AZP_URL
            - name: AZP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: AZP_TOKEN
            - name: AZP_POOL
              valueFrom:
                secretKeyRef:
                  name: azdevops
                  key: AZP_POOL
            - name: DOCKER_HOST  # Configuração para Docker-in-Docker
              value: "unix:///var/run/docker.sock"
          securityContext:
            privileged: true  # Necessário para habilitar Docker-in-Docker (DinD)
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-volume
      volumes:
        - name: docker-volume
          hostPath:
            path: /var/run/docker.sock
            type: Socket  # Define que o volume é do tipo socket
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: layer
                    operator: In
                    values:
                      - apps
      imagePullSecrets:
        - name: docker-credentials
