apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observabilidade
  namespace: plataforma-m-mais
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack  # Nome do Helm Chart
    targetRevision: 54.2.2  # Versão específica do chart
    helm:
      valueFiles:
        - namespace.yaml  # Arquivo de valores para namespaces
        - values-sandbox.yaml  # Valores específicos do ambiente sandbox
      values: |
        prometheus:
          service:
            type: ClusterIP
            port: 9090
          retention: 15d  # Exemplo: retenção ajustada para 15 dias
        alertmanager:
          enabled: true
        grafana:
          adminPassword: "admin"  # Definição de senha admin
          service:
            type: NodePort  # Tipo de serviço NodePort
            nodePort: 30000
  destination:
    server: https://kubernetes.default.svc
    namespace: observabilidade
  syncPolicy:
    automated:
      prune: true  # Remove recursos que não estão mais no Git
      selfHeal: true  # Corrige mudanças feitas manualmente
